@url = https://8080-eulaahsanto-gamesreposi-onpd7iwj5hu.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "PC"
}

###
GET {{url}}/plataformas/4