@url = https://8080-mikeeeevale-gamessw2202-jd0x35ewz1i.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "xbox"
}

###
GET {{url}}/plataformas/4